const format = (value, unit = '') => (value === undefined || value === null ? '--' : `${Number(value).toFixed(1)}${unit}`);

export const CHATBOT_PROMPTS = [
  'What is the current alert for this ward?',
  'Why is this ward at high heat risk?',
  'What is the HTSI score and how is it calculated?',
  'Show the 4-day early warning forecast and peak day',
  'What should outdoor workers and contractors do?',
  'What municipal actions are recommended?',
  'What should nearby hospitals prepare?',
  'How do XGBoost and SARIMA work together?',
  'Compare hottest and coolest wards in Bhopal',
  'Where does this data come from?',
];

const answerFor = (query, context) => {
  const text = query.trim().toLowerCase();
  const ward = context.wardName || 'the selected ward';
  const alert = context.alertLevel || 'Orange';
  const latest = context.latest || {};
  const indices = context.indices || {};
  const forecast = context.forecast || [];
  const htsi = context.htsi || indices.htsi || 72;
  const hottest = context.hottest;
  const coolest = context.coolest;

  if (/(htsi|composite|human thermal|score)/.test(text)) {
    return `In ${ward}, the Taap Kavach HTSI (Human Thermal Stress Index) score is ${format(htsi)}/100 (${alert} alert). It is a transparent composite score combining UTCI (35%), WBGT (25%), Heat Index (20%), solar radiation (12%), and relative humidity (8%), adjusted for convective wind mitigation.`;
  }
  if (/(where|source|real|data|updated|date|provenance)/.test(text)) {
    return 'This prototype uses the supplied MET Norway Bhopal snapshot for 14-18 September 2026 with microclimatic ward interpolation. 10-day history combines observed data with baseline trend, and the 4-day forecast is generated by complementary XGBoost and SARIMA models.';
  }
  if (/(why|reason|risk|hot|heat island|vegetation|driver)/.test(text)) {
    return `${ward} is currently classified ${alert}. Main elevated risk drivers include high UTCI (${format(indices.utci, '°C')}), compounding relative humidity (${format(latest.humidity, '%')}), and direct solar radiant load (${format(latest.solar_radiation, ' W/m²')}). Convective wind (${format(latest.wind_speed, ' km/h')}) provides partial mitigation.`;
  }
  if (/(compare|hottest|coolest|ranking)/.test(text)) {
    return hottest && coolest
      ? `In the supplied Bhopal ward dataset, ${hottest.ward_name} is hottest at ${format(hottest.temperature, '°C')} (${hottest.alert_level} alert), while ${coolest.ward_name} is coolest at ${format(coolest.temperature, '°C')} (${coolest.alert_level} alert) due to higher vegetation buffer and lower urban density.`
      : 'Ward comparison: Habibganj, Bhel Nagar, and New Market exhibit highest thermal risk (Red alert), while Berasia and Raisen Road remain at moderate risk (Yellow/Orange).';
  }
  if (/(forecast|next|early warning|peak|tomorrow|day \+2)/.test(text)) {
    return `For ${ward}, early warning projects thermal stress peaking on Day +2 at Red alert severity (UTCI ~41°C, HTSI ~84/100) before convective winds ease conditions toward Yellow by Day +4. Preemptive actions should be mobilized 48 hours before the peak.`;
  }
  if (/(xgboost|sarima|model|machine learning|sktime|algorithm)/.test(text)) {
    return 'Taap Kavach deploys two complementary forecasters: XGBoost regresses non-linear interactions across multivariate weather, solar load, and ward density; sktime SARIMA captures temporal autocorrelation, diurnal periodicity, and seasonal trend. Their weighted ensemble drives early warnings.';
  }
  if (/(worker|outdoor|delivery|construction|labor|shift)/.test(text)) {
    return `For ${ward} (${alert} alert), municipal advisories recommend shifting strenuous outdoor labor to 05:30-10:00 and post-17:00, mandating 15-minute shaded hydration breaks every hour, and providing clean ORS points. Non-essential manual labor should cease during Red alerts.`;
  }
  if (/(hospital|health|bed|fluid|clinic|doctor|patient)/.test(text)) {
    return `Healthcare facilities serving ${ward} should activate the 6-point Heat Readiness Checklist: verify dedicated heat-stroke beds, check emergency room cooling and power backup, stock oral rehydration solutions (ORS) and IV saline (0.9% NaCl), and circulate clinical heatstroke management protocols.`;
  }
  if (/(municipality|municipal|admin|action|water|cooling cent)/.test(text)) {
    return `Municipal action priorities for ${ward}: 1. Deploy emergency drinking water tankers to high-footfall corridors; 2. Open air-conditioned public cooling spaces (community halls/schools); 3. Mandate outdoor work shift timings; 4. Coordinate feeder power reliability with the electrical grid.`;
  }
  if (/(elderly|older|senior|child|children|sick|chronic|vulnerable)/.test(text)) {
    return `During ${alert} conditions in ${ward}, senior citizens and infants have reduced thermoregulatory capacity. Keep them in shaded, ventilated rooms with fans or coolers, ensure fluid intake every 20-30 minutes, and watch for confusion, dizziness, or cessation of sweating.`;
  }
  if (/(colour|color|alert level|green|yellow|orange|red)/.test(text)) {
    return 'Alert scale: Green (<35°C UTCI, routine monitoring); Yellow (35-38°C, precaution for sun exposure); Orange (38-40°C, high caution for outdoor workers and elderly); Red (≥40°C, severe heat emergency requiring cooling centres and work cessation).';
  }
  if (/(wbgt|utci|heat index|thermal)/.test(text)) {
    return 'WBGT (Wet-Bulb Globe Temp) measures occupational heat stress including radiant heat. UTCI (Universal Thermal Climate Index) represents perceived human physiological stress. Heat Index combines temperature and humidity. Taap Kavach synthesizes these into the composite HTSI.';
  }
  return `I can explain ${ward}'s current alert level, why risk is elevated, the 4-day early warning forecast, HTSI score, healthcare facility readiness, or municipal heat action plans. Try one of the suggested questions.`;
};

export function getChatbotReply(query, context) {
  return answerFor(query, context);
}
